-- Migration 010: Update email templates to remove buttons and rebrand to Trenor
-- This migration updates email templates to:
-- 1. Remove buttons from HTML content
-- 2. Replace "Industrial" with "Trenor" 
-- 3. Update website URL to https://www.trenor.com.mx/

-- Update client_quote_confirmation template
UPDATE email_templates 
SET 
    subject = 'Confirmación de Solicitud de Cotización - {{quote_number}}',
    html_content = CONCAT(
        '<!DOCTYPE html>',
        '<html lang="es">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<title>Confirmación de Cotización</title>',
        '<style>',
        'body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4; margin: 0; padding: 0; }',
        '.container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }',
        '.header { background: linear-gradient(135deg, #2c5aa0 0%, #1a365d 100%); color: white; padding: 30px; text-align: center; }',
        '.header img { max-height: 50px; margin-bottom: 15px; }',
        '.content { padding: 30px; }',
        '.quote-box { background-color: #f8f9fa; border-left: 4px solid #c03818; padding: 20px; margin: 20px 0; }',
        '.product-details { background-color: #fff; border: 1px solid #e9ecef; border-radius: 8px; padding: 20px; margin: 20px 0; }',
        '.footer { background-color: #2c5aa0; color: white; padding: 20px; text-align: center; font-size: 14px; }',
        '.contact-info { background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 15px; margin: 20px 0; }',
        '</style>',
        '</head>',
        '<body>',
        '<div class="container">',
        '<div class="header">',
        '<img src="{{company_logo}}" alt="{{company_name}}">',
        '<h1>¡Gracias por tu solicitud!</h1>',
        '<p>Tu cotización ha sido recibida exitosamente</p>',
        '</div>',
        '<div class="content">',
        '<h2>Hola {{customer_name}},</h2>',
        '<p>Hemos recibido tu solicitud de cotización y nuestro equipo la está revisando. Te responderemos dentro de las próximas horas.</p>',
        '<div class="quote-box">',
        '<h3>📋 Detalles de tu Solicitud</h3>',
        '<p><strong>Número de Cotización:</strong> {{quote_number}}</p>',
        '<p><strong>Fecha:</strong> {{date}}</p>',
        '</div>',
        '<div class="product-details">',
        '<h3>🔧 Información del Producto</h3>',
        '{{#if brand}}<p><strong>Marca:</strong> {{brand}}</p>{{/if}}',
        '{{#if product_type}}<p><strong>Tipo de Producto:</strong> {{product_type}}</p>{{/if}}',
        '{{#if part_number}}<p><strong>Número de Parte:</strong> {{part_number}}</p>{{/if}}',
        '{{#if specifications}}<p><strong>Especificaciones:</strong> {{specifications}}</p>{{/if}}',
        '</div>',
        '<div class="contact-info">',
        '<p><strong>📞 Información de Contacto Registrada:</strong></p>',
        '<p>Email: {{customer_email}}</p>',
        '{{#if customer_phone}}<p>Teléfono: {{customer_phone}}</p>{{/if}}',
        '{{#if customer_company}}<p>Empresa: {{customer_company}}</p>{{/if}}',
        '<p>Método de contacto preferido: {{preferred_contact_method}}</p>',
        '</div>',
        '<p>Un asesor de <strong>{{company_name}}</strong> se pondrá en contacto contigo a la brevedad para brindarte la información que necesitas.</p>',
        '<p style="text-align: center; margin-top: 30px;">',
        '<strong>Visita nuestro sitio web:</strong><br>',
        '<a href="https://www.trenor.com.mx/" style="color: #c03818; text-decoration: none;">https://www.trenor.com.mx/</a>',
        '</p>',
        '</div>',
        '<div class="footer">',
        '<p>&copy; 2024 {{company_name}}. Todos los derechos reservados.</p>',
        '<p>Herramientas profesionales, equipamiento Trenor y componentes de precisión</p>',
        '</div>',
        '</div>',
        '</body>',
        '</html>'
    ),
    text_content = CONCAT(
        'Hola {{customer_name}},',
        '\n\n',
        'Hemos recibido tu solicitud de cotización y nuestro equipo la está revisando.',
        '\n\n',
        'Detalles de tu Solicitud:',
        '\n- Número de Cotización: {{quote_number}}',
        '\n- Fecha: {{date}}',
        '\n\n',
        'Información del Producto:',
        '\n{{#if brand}}- Marca: {{brand}}{{/if}}',
        '\n{{#if product_type}}- Tipo de Producto: {{product_type}}{{/if}}',
        '\n{{#if part_number}}- Número de Parte: {{part_number}}{{/if}}',
        '\n{{#if specifications}}- Especificaciones: {{specifications}}{{/if}}',
        '\n\n',
        'Un asesor de {{company_name}} se pondrá en contacto contigo a la brevedad.',
        '\n\n',
        'Visita nuestro sitio web: https://www.trenor.com.mx/',
        '\n\n',
        'Saludos,',
        '\nEquipo {{company_name}}'
    )
WHERE template_key = 'client_quote_confirmation';

-- Update admin_quote_notification template  
UPDATE email_templates
SET 
    subject = 'Nueva Solicitud de Cotización - {{quote_number}}',
    html_content = CONCAT(
        '<!DOCTYPE html>',
        '<html lang="es">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<title>Nueva Cotización</title>',
        '<style>',
        'body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4; margin: 0; padding: 0; }',
        '.container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }',
        '.header { background: linear-gradient(135deg, #c03818 0%, #d94520 100%); color: white; padding: 30px; text-align: center; }',
        '.header img { max-height: 50px; margin-bottom: 15px; }',
        '.content { padding: 30px; }',
        '.alert-box { background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 20px; margin: 20px 0; }',
        '.client-info { background-color: #f8f9fa; border: 1px solid #e9ecef; border-radius: 8px; padding: 20px; margin: 20px 0; }',
        '.product-info { background-color: #e8f4fd; border: 1px solid #bee5eb; border-radius: 8px; padding: 20px; margin: 20px 0; }',
        '.footer { background-color: #2c5aa0; color: white; padding: 20px; text-align: center; font-size: 14px; }',
        '.urgent { color: #c03818; font-weight: bold; }',
        '.contact-links { text-align: center; margin: 30px 0; }',
        '.contact-links a { color: #c03818; text-decoration: none; margin: 0 10px; font-weight: bold; }',
        '</style>',
        '</head>',
        '<body>',
        '<div class="container">',
        '<div class="header">',
        '<img src="{{company_logo}}" alt="{{company_name}} Admin">',
        '<h1>🚨 Nueva Solicitud de Cotización</h1>',
        '<p>Requiere atención inmediata</p>',
        '</div>',
        '<div class="content">',
        '<div class="alert-box">',
        '<p class="urgent">⚡ Solicitud recibida: {{date}}</p>',
        '<p><strong>Número de Cotización:</strong> {{quote_number}}</p>',
        '</div>',
        '<div class="client-info">',
        '<h3>👤 Información del Cliente</h3>',
        '<p><strong>Nombre:</strong> {{customer_name}}</p>',
        '<p><strong>Email:</strong> {{customer_email}}</p>',
        '{{#if customer_phone}}<p><strong>Teléfono:</strong> {{customer_phone}}</p>{{/if}}',
        '{{#if customer_company}}<p><strong>Empresa:</strong> {{customer_company}}</p>{{/if}}',
        '{{#if city_state}}<p><strong>Ubicación:</strong> {{city_state}}</p>{{/if}}',
        '<p><strong>Método de contacto preferido:</strong> {{preferred_contact_method}}</p>',
        '</div>',
        '<div class="product-info">',
        '<h3>🔧 Detalles del Producto Solicitado</h3>',
        '{{#if brand}}<p><strong>Marca:</strong> {{brand}}</p>{{/if}}',
        '{{#if product_type}}<p><strong>Tipo de Producto:</strong> {{product_type}}</p>{{/if}}',
        '{{#if part_number}}<p><strong>Número de Parte:</strong> {{part_number}}</p>{{/if}}',
        '{{#if specifications}}<p><strong>Especificaciones:</strong> {{specifications}}</p>{{/if}}',
        '{{#if quantity}}<p><strong>Cantidad:</strong> {{quantity}}</p>{{/if}}',
        '{{#if customer_message}}<p><strong>Mensaje adicional:</strong> {{customer_message}}</p>{{/if}}',
        '</div>',
        '<p><strong>Siguiente paso:</strong> Contactar al cliente para proporcionar la cotización solicitada.</p>',
        '</div>',
        '<div class="footer">',
        '<p>Panel de Administración {{company_name}}</p>',
        '<p>Este email fue generado automáticamente por el sistema de cotizaciones Trenor</p>',
        '</div>',
        '</div>',
        '</body>',
        '</html>'
    ),
    text_content = CONCAT(
        'Nueva Solicitud de Cotización - {{quote_number}}',
        '\n\n',
        'Solicitud recibida: {{date}}',
        '\n\n',
        'INFORMACIÓN DEL CLIENTE:',
        '\n- Nombre: {{customer_name}}',
        '\n- Email: {{customer_email}}',
        '\n{{#if customer_phone}}- Teléfono: {{customer_phone}}{{/if}}',
        '\n{{#if customer_company}}- Empresa: {{customer_company}}{{/if}}',
        '\n{{#if city_state}}- Ubicación: {{city_state}}{{/if}}',
        '\n- Método de contacto preferido: {{preferred_contact_method}}',
        '\n\n',
        'PRODUCTO SOLICITADO:',
        '\n{{#if brand}}- Marca: {{brand}}{{/if}}',
        '\n{{#if product_type}}- Tipo de Producto: {{product_type}}{{/if}}',
        '\n{{#if part_number}}- Número de Parte: {{part_number}}{{/if}}',
        '\n{{#if specifications}}- Especificaciones: {{specifications}}{{/if}}',
        '\n{{#if quantity}}- Cantidad: {{quantity}}{{/if}}',
        '\n{{#if customer_message}}- Mensaje: {{customer_message}}{{/if}}',
        '\n\n',
        'Accede al panel admin para gestionar esta cotización.',
        '\nPanel: {{admin_url}}/quotes/{{quote_id}}',
        '\n\n',
        'Sistema {{company_name}}'
    )
WHERE template_key = 'admin_quote_notification';